version: '3.4'
services:
  grafana:
    image: grafana/grafana
    container_name: myop-grafana-dashboard
    ports:
      - 80:3000
    volumes:
      # - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
    depends_on:
      - graphite
  statsd:
    build: ./statsd
    container_name: myop-statsd
    environment: 
      - GRAPHITE_PORT_2003_TCP_ADDR=graphite
    ports:
      - "8125:8125/udp"
      - "8126:8126"
  graphite:
    build: ./graphite
    image: myoperator/graphite_statsd
    container_name: myop-graphite-carbon
    ports:
      - "8080:80"
    environment: 
      - GRAPHITE_STATSD_HOST=statsd
    expose: 
      - 8080
      - "2003-2004"
      - "2023-2024"
    volumes:
      # - graphite_data:/opt/graphite/storage
      - ./log/graphite:/var/log/graphite
    depends_on:
      - statsd

  weatherapi:
    build:
      context: ./src/StatsWeb.Api/
      dockerfile: Dockerfile
    ports:
      - "8081:80"

# volumes:
#     grafana_data: {}
#     graphite_data: {}