version: '2'

services:
  web:
    extends:
      service: base
      file: docker-compose-base.yml
    command: sh -c "cabot migrate && gunicorn cabot.wsgi:application -b 0.0.0.0:5000 --workers=5"
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  worker:
    extends:
      service: base
      file: docker-compose-base.yml
    command: celery worker -A cabot
    depends_on:
      - web
      - postgres
      - rabbitmq
    restart: always

  beat:
    extends:
      service: base
      file: docker-compose-base.yml
    command: celery beat -A cabot
    depends_on:
      - web
      - postgres
      - rabbitmq
    restart: always
  
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.6-alpine
    restart: always

volumes:
  data:
