{
 "title": "Prometheus vs Graphite",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count of Requests - Graphite",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "hitcount(stats.weather.weather_request_total, '1m')"
    }
   ]
  },
  {
   "title": "Sumarize - Graphite",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(stats.weather.weather_request_total, '60s', 'sum', false)"
    }
   ]
  },
  {
   "title": "Count of Requests - Prometheus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(weather_request_total[1m]))"
    }
   ]
  },
  {
   "title": "Rate - Prometheus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(weather_request_total[1m]))"
    }
   ]
  }
 ]
}